id: alien4cloud-datagouv_mls-plugin
name: Datagouv-MLS plugin
version: ${project.version}
description: >
  This plugin publishes info to Datagouv-MLS
configuration_class: org.alien4cloud.plugin.datagouv_mls.PluginConfiguration
component_descriptors:
  - bean_name: datagouv_mls-module-import
    name: Datagouv-MLS / modules import
    description: >
      Plugin that publishes info about imported modules
  - bean_name: datagouv_mls-module-delete
    name: Datagouv-MLS / modules delete
    description: >
      Plugin that publishes info about deleted modules
  - bean_name: datagouv_mls-pre_match-modifier
    name: Datagouv-MLS / applications deployment (pre-match)
    description: >
      Plugin that prepares data for datagouv_mls-modifier
  - bean_name: datagouv_mls-modifier
    name: Datagouv-MLS / applications deployment (post-match)
    description: >
      Plugin that publishes info about applications to be deployed
  - bean_name: datagouv_mls-listener
    name: Datagouv-MLS / applications deployment and undeployment
    description: >
      Plugin that publishes info about applications deployment and undeployment

