id: alien4cloud-datagouv_mls-plugin
name: Datagouv-MLS plugin
version: ${project.version}
description: >
  This plugin publishes info to Datagouv-MLS
configuration_class: org.alien4cloud.plugin.datagouv_mls.PluginConfiguration
component_descriptors:
  - bean_name: datagouv_mls-module-import
    name: Datagouv-MLS / modules import
    description: >
      Plugin that publishes info about imported modules
  - bean_name: datagouv_mls-module-delete
    name: Datagouv-MLS / modules delete
    description: >
      Plugin that publishes info about deleted modules
  - bean_name: datagouv_mls-modifier
    name: Datagouv-MLS / applications deployment
    description: >
      Plugin that publishes info about applications to be deployed
  - bean_name: datagouv_mls-listener
    name: Datagouv-MLS / applications deployment and undeployment
    description: >
      Plugin that publishes info about applications deployment and undeployment
  - bean_name: datagouv_mls-redirection-sample
    name: Datagouv-MLS / Redirection sample
    description: >
      Modifier to experiment redirection (randomly google search for a number)
  - bean_name: metapropscheck-modifier
    name: Datagouv-MLS / Meta Properties checker
    description: >
      Modifier to check that application mandatory metaproperties are set
  - bean_name: property-suggestion-provider
    name: Property suggestions provider
    description: >
      Suggest values got from URL
